<a href="https://colab.research.google.com/github/VladyValle/gh-first-action/blob/master/AlgebraLineal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Reduced Row Echelon Form (RREF) of an Augmented Matrix

In [12]:
import numpy as np
import sympy
from IPython.display import Math, display

# Define an example augmented matrix using NumPy
example_matrix_np = np.array([
    [1, 0, 5, 2],
    [-2, 1, -6, -1],
    [-0, 2, 8, 6]
])

print("Original NumPy Matrix:")
print(example_matrix_np)

# Convert NumPy matrix to SymPy Matrix
example_matrix_sympy = sympy.Matrix(example_matrix_np)

# Calculate the RREF using SymPy
rref_result_sympy, pivots = example_matrix_sympy.rref()

print("\nMatrix in RREF (using SymPy):")
display(Math(sympy.latex(rref_result_sympy)))

Original NumPy Matrix:
[[ 1  0  5  2]
 [-2  1 -6 -1]
 [ 0  2  8  6]]

Matrix in RREF (using SymPy):


<IPython.core.display.Math object>